
# Array



## Find the First Duplicate Element

Given an integer array nums, write a function that returns the first duplicate element, or -1 if no duplicate exists. The first duplicate is the one that appears first in the order of appearance in the array.

### Example:

- Input: nums = [1, 2, 3, 4, 2, 5]
- Output: 2

- Input: nums = [1, 2, 3, 4, 5]
- Output: -1

In [ ]:
def findFirstDuplicate(nums):
  hash_table =[]
  for i in nums:
    if i in hash_table:
      return i
    hash_table.append(i)

  return None


In [ ]:
nums = [1, 1, 3, 4, 1, 5]
print(findFirstDuplicate(nums))

1


## Count Even and Odd Numbers

Given an integer array nums, write a function that counts the number of even and odd numbers in the array and returns the counts.

### Example:

- Input: nums = [1, 2, 3, 4, 5, 6]
- Output: (3, 3)  # 3 even numbers, 3 odd numbers

In [ ]:
def countEvenOdd(nums) :
  even = 0
  odds = 0
  for i in nums:
    if (i % 2) == 0 :
      even +=1
    else :
      odds += 1

  return ((even,odds))


In [ ]:
nums=  [1, 2, 3, 4, 5, 6]
print(countEvenOdd(nums))

(3, 3)


## Single Number

Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.*

- Example 1:
  - *Input*: nums = [2,2,1]*texte en italique*
  - *Output*: 1
- Example 2:
  - *Input*: nums = [4,1,2,1,2]
  - *Output*: 4

In [ ]:
def singleNumber(nums) :
  out = 0
  for i in nums :
    out = i ^ out

  return out






In [ ]:
nums = [4,1,2,1,2]
print(singleNumber(nums))  # Output: 4

4


## Find the Missing Number in a Sequence
Given an array nums containing n distinct numbers in the range [0, n], find the missing number.

### Example:

- Input: nums = [3, 0, 1]
- Output: 2

In [ ]:
def findMissingNumber(nums):
  for i in range(len(nums) +1):
    if i not in nums:
      return i
  return None


In [ ]:
nums =  [0,3,1] #output 5
print (findMissingNumber(nums))

2


## Reverse an Array

Given an integer array nums, write a function that reverses the array in place.

### Example:


- Input: nums = [1, 2, 3, 4, 5]
- Output: [5, 4, 3, 2, 1]

In [ ]:
def reverseArray(nums):
  size = len(nums)
  out = [0]*size
  for i in range(size):
    out[i] = nums[size -(i+1)]

  return out

In [ ]:
nums = [1, 2, 3, 4, 5]
print(reverseArray(nums))

[5, 4, 3, 2, 1]


In [ ]:
a = [1, 2, 3, 4, 5]
a[-1:] + a[:-1]

[5, 1, 2, 3, 4]

# Numpy


## Mean of Each Row

Write a function row_means(matrix) that takes a 2D NumPy array matrix and returns a 1D array with the mean of each row.

Example:


- Input:


```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

```


- Output:

```
[2. 5. 8.]

```



In [ ]:
def row_means(matrix):
 output = np.apply_along_axis(np.mean,axis=1, arr= matrix)
 return output


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(row_means(matrix))  # Output: [2. 5. 8.]

[2. 5. 8.]


In [ ]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Replace Negative Values with Zero

Write a function replace_negative_with_zero(arr) that takes a NumPy array arr and returns a new array where all negative values are replaced by 0.

- Input: [-1, 2, -3, 4]
- Output: [0, 2, 0, 4]

In [ ]:
import numpy as np
def replace_negative_with_zero(nums):
  nums[nums<0] = 0
  return nums


In [ ]:
arr = np.array([-1, 2, -3, 4])
print(replace_negative_with_zero(arr))  # Output: [0, 2, 0, 4]

[0 2 0 4]


## Sum of Diagonal Elements
Write a function sum_diagonal(matrix) that takes a 2D NumPy array matrix and returns the sum of its diagonal elements.

- Input:

```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]

```



- Output: 15

In [ ]:
def sum_diagonal(matrix):
  output = np.diagonal(matrix).sum()
  return output

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(sum_diagonal(matrix))  # Output: 15

15


# Class and Object-oriented programming (OOP)

## Define a Simple Class

Create a class Rectangle with two attributes: length and width. The class should have:

1. A constructor that initializes the attributes.
2. A method area() that returns the area of the rectangle.
3. A method perimeter() that returns the perimeter of the rectangle.

- Example:


```
rect = Rectangle(5, 10)
print(rect.area())      # Output: 50
print(rect.perimeter()) # Output: 30
```



In [27]:
class Rectangle:
  def __init__(self, length, width):
    self.length = length
    self.width = width

  def area(self):
    self.area = (self.length* self.width)
    return self.area

  def perimeter(self):
    self.perimeter = (self.length+ self.width)*2
    return self.perimeter


class Maison(Rectangle):
  def __init__(self, length, width):
    super().__init__(length, width)

  def dagbachi(self):
    perimeter = super().perimeter()
    print(f"Ta maison est DIGBA DEH VIEUX!!! {perimeter} m2 TChiaaaa")

In [28]:
maison = Maison(5, 10)
print(maison.area())      # Output: 50
print(maison.perimeter()) # Output: 30
maison.dagbachi()

50
30
Ta maison est DIGBA DEH VIEUX!!! 30 m2 TChiaaaa


## Class Inheritance

Create a class Person with attributes name and age, and a method display() that prints the person's details.

Create a subclass Student that inherits from Person, and adds an attribute grade. Override the display() method to include the student's grade.

- Example



```
student = Student("Alice", 20, "A")
student.display() # Output: Name: Alice, Age: 20, Grade: **A**
```





In [23]:
class Person:
  def __init__(self, name, age) -> None:
    self.name= name
    self.age = age

  def display(self):
    print(f"Name : {self.name}, Age : {self.age}")

  def atalakou(self):
    print(f"You are awesome {self.name} !!!!!!!")


class Student(Person):
  def __init__(self, name, age, grade) -> None:
    super().__init__(name, age)
    self.grade = grade

  def display(self):
    print(f"Name: {self.name}, Age: {self.age}, Grade: {self.grade}")

  def atalakou(self):
    return super().atalakou()

In [24]:
student = Student("Alice", 20, "A")
student.display()  # Output: Name: Alice, Age: 20, Grade: A
student.atalakou()

Name: Alice, Age: 20, Grade: A
You are awesome Alice !!!!!!!
